# Generated by Django 5.2.17 on 2026-09-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('reconciliation_month', models.CharField(max_length=20)),
                ('two_b_file', models.FileField(upload_to='uploads/2b/')),
                ('purchase_file', models.FileField(upload_to='uploads/purchase/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Uploaded', max_length=30)),
            ],
        ),
    ]
