# Generated by Django 5.2.17 on 2026-09-29 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_masterconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite_key', models.CharField(db_index=True, max_length=500)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('two_b_taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('purchase_taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('two_b_igst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('purchase_igst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('two_b_cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('purchase_cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('two_b_sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('purchase_sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('original_status', models.CharField(max_length=50)),
                ('current_status', models.CharField(max_length=50)),
                ('manual_status', models.BooleanField(default=False)),
                ('changed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_results', to='reconciliation.uploadbatch')),
            ],
        ),
    ]
