# Generated by Django 5.2.17 on 2026-09-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_reconciliationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationresult',
            name='cgst_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='igst_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='sgst_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='taxable_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
