# Generated by Django 5.2.17 on 2026-10-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_reconciliationresult_cgst_difference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='modified_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='modified_file',
            field=models.FileField(blank=True, null=True, upload_to='update/'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='purchase_file',
            field=models.FileField(upload_to='purchase_file/'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='two_b_file',
            field=models.FileField(upload_to='two_b_file/'),
        ),
    ]
