# Generated by Django 5.2.17 on 2026-10-05 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0005_uploadbatch_modified_at_uploadbatch_modified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_month', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('document_number', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('invoice_number_supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_invoice_date', models.DateField(blank=True, null=True)),
                ('ledger_description', models.CharField(blank=True, max_length=500, null=True)),
                ('business_partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_description', models.CharField(blank=True, max_length=500, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('igst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_code', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_code', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('company_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ledger_code', models.CharField(blank=True, max_length=100, null=True)),
                ('bp_code', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('remark2', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_data', to='reconciliation.uploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='TwoBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_b_month', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('gstin_of_supplier', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_type', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('reverse_charge', models.CharField(blank=True, max_length=50, null=True)),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('integrated_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('central_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('state_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cess', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('filing_period', models.CharField(blank=True, max_length=100, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('itc_availability', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('irn', models.CharField(blank=True, max_length=255, null=True)),
                ('irn_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_b_data', to='reconciliation.uploadbatch')),
            ],
        ),
    ]
